changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "Breaking Changes :boom:"
      labels:
        - breaking-change
    - title: "New Features :sparkles:"
      labels:
        - enhancement
    - title: "Bug Fixes :bug:"
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
