name: Bot commands
on: issue_comment

jobs:
  permissions:
    name: Check Permissions
    runs-on: ubuntu-latest
    steps:
      - name: Check association
        run: |
          allowed=("OWNER" "COLLABORATOR")
          value="\<${{ github.event.issue.author_association }}\>"
        
          if [[ ${allowed[@]} =~ $value ]]
          then
            exit 0
          else
            exit 1
          fi

  load_vars:
    uses: ./.github/workflows/build_vars.yml

  run-all_tests:
    name: All Tests
    if: >
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '/run tests')
    permissions:
      contents: read
      packages: write
      statuses: write
    needs:
      - permissions
    uses: ./.github/workflows/tests.yml
    with:
      pr: ${{ github.event.issue.number }}
      parent_job_name: Run All Tests
    secrets:
      RH_REPO: ${{ secrets.RH_REPO }}
      RH_ENT: ${{ secrets.RH_ENT }}

  run_build_container:
    name: Run Build Container
    if: >
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '/run build container')
    permissions:
      contents: read
      packages: write
      statuses: write
    needs:
      - permissions
    uses: ./.github/workflows/build_container.yml
    with:
      pr: ${{ github.event.issue.number }}
      parent_job_name: Run Build Container
    secrets:
      RH_REPO: ${{ secrets.RH_REPO }}
      RH_ENT: ${{ secrets.RH_ENT }}

  run_build_iso:
    name: Run Build ISO
    if: >
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '/run build iso')
    permissions:
      contents: read
      packages: write
      statuses: write
    needs:
      - permissions
    uses: ./.github/workflows/build_iso.yml
    with:
      pr: ${{ github.event.issue.number }}
      parent_job_name: Run Build ISO

  run_build_iso_rhel:
    name: Run Build RHEL ISO
    if: >
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '/run build iso')
    permissions:
      contents: read
      packages: write
      statuses: write
    needs:
      - permissions
    uses: ./.github/workflows/build_iso_rhel.yml
    with:
      pr: ${{ github.event.issue.number }}
      parent_job_name: Run Build ISO
    secrets:
      RH_REPO: ${{ secrets.RH_REPO }}
      RH_ENT: ${{ secrets.RH_ENT }}

  run_test_iso:
    name: Run ISO Tests
    permissions:
      contents: read
      packages: write
      statuses: write
    needs:
      - permissions
      - load_vars
      - run_build_iso
    uses: ./.github/workflows/test_iso.yml
    with:
      pr: ${{ github.event.issue.number }}
      parent_job_name: Run ISO Tests

  run_test_deployment:
    name: Run ISO Deployment Tests
    permissions:
      contents: read
      packages: write
      statuses: write
    needs:
      - permissions
      - load_vars
      - run_build_iso
    uses: ./.github/workflows/test_deployment.yml
    with:
      pr: ${{ github.event.issue.number }}
      parent_job_name: Run ISO Deployment Tests
