name: Build Vars

on:
  workflow_call:
    outputs:
      ARCH:
        value: 'x86_64'
      BUILD_VERSIONS:
        value: '[8]'
      IMAGE_NAME:
        value: 'fedora-bootc'
      IMAGE_REPO:
        value: 'quay.io/centos-bootc'
      IMAGE_TAG:
        value: 'eln'
      VARIANT:
        value: 'Server'
      SECURE_BOOT_KEY_URL:
        value: 'https://github.com/ublue-os/akmods/raw/main/certs/public_key.der'
      ENROLLMENT_PASSWORD:
        value: 'container-installer'
      

jobs:
  load-vars:
    name: Load Variables
    runs-on: ubuntu-latest
    steps:
      - name: Sucess
        run:
          echo "Vars loaded"
