name: All Tests

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  workflow_dispatch:

  workflow_call:
    inputs:
      pr:
        required: true
        type: string
      parent_job_name:
        required: true
        type: string
      

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_container:
    name: Build Container
    uses: ./.github/workflows/build_container.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Build Container
  
  build_isos:
    name: Build ISOs
    needs:
      - build_container
    uses: ./.github/workflows/build_iso.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Build ISOs

  test_isos:
    name: Test ISOs
    needs:
      - build_isos
    uses: ./.github/workflows/test_iso.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Test ISOs

  test_deployments:
    name: Test Deployments
    needs:
      - build_isos
    uses: ./.github/workflows/test_deployment.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Test Deployments
