name: Tests

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  workflow_call:
    inputs:
      pr:
        required: true
        type: string
      parent_job_name:
        required: true
        type: string
      

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_container:
    name: Build Container
    uses: ./.github/workflows/build_container.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Build Container
  
  build_iso:
    name: Build ISO
    needs:
      - build_container
    uses: ./.github/workflows/build_iso.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Build ISO

  test_iso:
    name: Test ISO
    needs:
      - build_iso
    uses: ./.github/workflows/test_iso.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Test ISO
      iso_name-38: ${{ needs.build_iso.outputs.iso_name-38 }}
      iso_name-39: ${{ needs.build_iso.outputs.iso_name-39 }}
      iso_name-40: ${{ needs.build_iso.outputs.iso_name-40 }}

  test_deployment:
    name: Test Deployment
    needs:
      - build_iso
    uses: ./.github/workflows/test_deployment.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Test Deployment
      iso_name-38: ${{ needs.build_iso.outputs.iso_name-38 }}
      iso_name-39: ${{ needs.build_iso.outputs.iso_name-39 }}
      iso_name-40: ${{ needs.build_iso.outputs.iso_name-40 }}