name: All Tests

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  workflow_dispatch:

  workflow_call:
    inputs:
      pr:
        required: true
        type: string
      parent_job_name:
        required: true
        type: string
    secrets:
      RH_REPO: 
        required: true
      RH_ENT:
        required: true
      

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_container:
    name: Build Container
    uses: ./.github/workflows/build_container.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Build Container
    secrets:
      RH_REPO: ${{ secrets.RH_REPO }}
      RH_ENT: ${{ secrets.RH_ENT }}
  
  build_iso_flatpaks:
    name: Build ISO with Flatpaks
    needs:
      - build_container
    uses: ./.github/workflows/build_iso.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Build ISO with Flatpaks
      flatpaks_refs_dir: flatpak_refs
      suffix: flatpaks
    secrets:
      RH_REPO: ${{ secrets.RH_REPO }}
      RH_ENT: ${{ secrets.RH_ENT }}

  test_iso_flatpaks:
    name: Test ISO with Flatpaks
    needs:
      - build_iso_flatpaks
    uses: ./.github/workflows/test_iso.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Test ISO with Flatpaks
      flatpaks_refs_dir: flatpak_refs
      suffix: flatpaks

  test_deployment_flatpaks:
    name: Test Deployment with Flatpaks
    needs:
      - build_iso_flatpaks
    uses: ./.github/workflows/test_deployment.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Test Deployment with Flatpaks
      flatpaks_refs_dir: flatpak_refs
      suffix: flatpaks

  build_iso_flatpak_refs:
    name: Build ISO with Flatpak Refs
    needs:
      - build_container
    uses: ./.github/workflows/build_iso.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Build ISO with Flatpak Refs
      flatpaks_refs: "app/org.mozilla.firefox/x86_64/stable app/org.videolan.VLC/x86_64/stable"
      suffix: flatpaks_refs
    secrets:
      RH_REPO: ${{ secrets.RH_REPO }}
      RH_ENT: ${{ secrets.RH_ENT }}

  test_iso_flatpak_refs:
    name: Test ISO with Flatpak Refs
    needs:
      - build_iso_flatpak_refs
    uses: ./.github/workflows/test_iso.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Test ISO with Flatpak Refs
      flatpaks_refs: "app/org.mozilla.firefox/x86_64/stable app/org.videolan.VLC/x86_64/stable"
      suffix: flatpaks_refs

  test_deployment_flatpak_refs:
    name: Test Deployment with Flatpak Refs
    needs:
      - build_iso_flatpak_refs
    uses: ./.github/workflows/test_deployment.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Test Deployment with Flatpak Refs
      flatpaks_refs: "app/org.mozilla.firefox/x86_64/stable app/org.videolan.VLC/x86_64/stable"
      suffix: flatpaks_refs

  build_iso:
    name: Build ISO
    needs:
      - build_container
    uses: ./.github/workflows/build_iso.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Build ISO
    secrets:
      RH_REPO: ${{ secrets.RH_REPO }}
      RH_ENT: ${{ secrets.RH_ENT }}

  test_iso:
    name: Test ISO
    needs:
      - build_iso
    uses: ./.github/workflows/test_iso.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Test ISO

  test_deployment:
    name: Test Deployment
    needs:
      - build_iso
    uses: ./.github/workflows/test_deployment.yml
    with:
      pr: ${{ inputs.pr }}
      parent_job_name: ${{ inputs.parent_job_name && format('{0} / ', inputs.parent_job_name) }}Test Deployment